spring:
  cloud:
    zookeeper:
      connect-string: 116.62.174.104:2181
      discovery:
        enabled: true
        instance-id: api-gateway
sofastack:
  auth:
    server:
      url: http://localhost:8033/login
management:
  endpoints:
    web:
      exposure:
        include: "*"